### ISSUE TITLE
old version request

### ISSUE THREAD

**Issue by BuistvoPloti** [CryDeS/Angel-Arena-Reborn#32]
hi guys, i remember those days around 2years ago when angel arena reborn was absolutely another game mod
for 2 years i've been noticing everyone in every single lobby complaining about current game mod and memorizing THE OLD DECENT VERSION OF THIS MOD
may i ask you on behalf of all true fans - please clone this mod and run two versions, the one which is current(basically the one you maintain), the second is the old one, with old maps and items, bosses etc, we can call it vanilla, which you don't need to maintain really(may be compatibility but no real maintain required) and it will be enough
thanks

**Comment by CryDeS** [comment]
I'am too lazy to do this, so if anyone want it - he can do it by himself(as far i know - someone doing this already). 
Also there anyway need to maintain project, due to valve patches(any valve patch broke gamemode, lol).
